---
abstract: 'convert Pod::PseudoPod documents into LaTeX'
author:
  - chromatic
build_requires:
  IO::String: 0
  Test::More: 0.60
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200009, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-PseudoPod-LaTeX
requires:
  File::Basename: 0
  File::Spec::Functions: 0
  Pod::PseudoPod: 0.16
  perl: 5.008006
resources:
  homepage: http://github.com/chromatic/Pod-PseudoPod-LaTeX
  repository: http://github.com/chromatic/Pod-PseudoPod-LaTeX.git
version: 1.20110710
